apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 924755424551.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 924755424551.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 924755424551.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 924755424551.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: b3e9948c
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
